server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
    username: root
    password: Admin123
    driver-classN-name: com.mysql.jdbc.Driver
    initialization-mode: always
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: INFO
      springframwork: DEBUG
